environment: development

server:
  hostname: 0.0.0.0
  port: 8080
  prefix:

database:
  host: localhost
  port: 5432
  user: postgres
  password: local_password
  database: bakalo
  timezone: Asia/Jakarta
  auto_migrate: true

smtp:
  host: mail.postale.io
  port: 587
  sender_name: Administrator Bakalo.li
  email: contact@bakalo.li
  password: PQ9Vgd4EiE4U

app:
  boards:
    pol:
      name: "Politik"
      shorthand: "pol"
      description: "Tempat berdiskusi politik dan berita politik terkini"
    teh:
      name: "Teknologi"
      shorthand: "teh"
      description: "Tempat berdiskusi teknologi seperti pemrograman, komputer, gadget, dan lainnya"
    oto:
      name: "Otomotif"
      shorthand: "oto"
      description: "Tempat berdiskusi otomotif"
    ipa:
      name: "Sains dan Matematika"
      shorthand: "ipa"
      description: "Tempat berdiskusi sains dan ilmu eksak lainnya"
    gim:
      name: "Video Games"
      shorthand: "gim"
      description: "Tempat berdiskusi video game terkini"
    mus:
      name: "Musik"
      shorthand: "mus"
      description: "Tempat berdiskusi musik terkini"
    ora:
      name: "Olahraga"
      shorthand: "ora"
      description: "Tempat berdiskusi olahraga"
    tvf:
      name: "TV & Film"
      shorthand: "tvf"
      description: "Tempat berdiskusi film terkini"
    wib:
      name: "Anime & Manga"
      shorthand: "wib"
      description: "Tempat berdiskusi anime dan manga terkini"
    par:
      name: "Paranormal"
      shorthand: "par"
      description: "Tempat berdiskusi Paranormal"
    biz:
      name: "Bisnis & Keuangan"
      shorthand: "biz"
      description: "Tempat berdiskusi bisnis & keuangan"
