version: "3"

services:
  media_server:
    image: halverneus/static-file-server
    environment:
      CORS: "false"
      FOLDER: "/media"
    volumes:
      - "../media:/media"
    ports:
      - "8081:8080"
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "local_password"
      POSTGRES_DB: "bakalo"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

volumes:
  postgres_data: