version: "3"

services:
  client:
    image: okkariswana/bakalo-client:latest
    environment:
      VIRTUAL_HOST: "staging.bakalo.li"
      LETSENCRYPT_HOST: "staging.bakalo.li"
      VIRTUAL_PORT: "80"
      DEFAULT_EMAIL: "okka.riswana@protonmail.com"
    ports:
      - "18082:80"
    depends_on:
      - web_server

  web_server:
    image: okkariswana/bakalo:latest
    environment:
      CONFIG_FILE: "/app/config.prod.yml"
      VIRTUAL_HOST: "staging.api.bakalo.li"
      LETSENCRYPT_HOST: "staging.api.bakalo.li"
      VIRTUAL_PORT: "8080"
      DEFAULT_EMAIL: "okka.riswana@protonmail.com"
    command: "sh -c './bakalo migrate && ./bakalo serve'"
    volumes:
      - "./config.prod.yml:/app/config.prod.yml"
      - "./media:/app/media"
    ports:
      - "18080:8080"
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "local_password"
      POSTGRES_DB: "bakalo"
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
    ports:
      - "15432:5432"

  media_server:
    image: halverneus/static-file-server
    environment:
      CORS: "true"
      FOLDER: "/media"
      VIRTUAL_HOST: "staging.media.bakalo.li"
      LETSENCRYPT_HOST: "staging.media.bakalo.li"
      VIRTUAL_PORT: "8080"
      DEFAULT_EMAIL: "okka.riswana@protonmail.com"
    volumes:
      - "./media:/media"
    ports:
      - "18081:8080"

networks:
  default:
    external:
      name: nginx-proxy

