version: "3"

services:
  web_server:
    image: okkariswana/bakalo:latest
    environment:
      CONFIG_FILE: "/app/config.prod.yml"
    volumes:
      - "./config.prod.yml:/app/config.prod.yml"
      - "./media:/app/media"
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "local_password"
      POSTGRES_DB: "bakalo"
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  media_server:
    image: halverneus/static-file-server
    environment:
      CORS: "false"
      FOLDER: "/media"
    volumes:
      - "./media:/media"
    ports:
      - "8081:8080"